[package]
name = "nexus_mcp"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nexus-mcp-server"
path = "src/bin/server.rs"

[dependencies]
clap = { version = "4", features = ["derive", "env"] }
rmcp = { version = "0.8.5", features = ["macros", "server", "transport-io", "transport-streamable-http-server"] }
tokio = { version = "1", features = ["full"] }
tokio-util = { version = "0.7" }
axum = { version = "0.8", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
reqwest = { workspace = true, features = ["json"] }
dotenv = "0.15"
thiserror = "1"
regex = "1"
x_toolbox = { path = "../x_toolbox" }
