[workspace]
members = ["src/nexus_voice","src/nexus_core"]
resolver = "2"

[workspace.dependencies]
reqwest = { version = "0.12", features = ["json", "stream"] }
tokio = { version = "1", features = ["full"] }
clap = { version = "4", features = ["derive"] }
ratatui = "0.28"
tokio-stream = "0.1"
uuid = { version = "1", features = ["v4", "serde"] }
quick-xml = { version = "0.33", features = ["serialize"] }
