[package]
name = "nexus-core"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nexus-core"
path = "src/main.rs"

[lib]
name = "nexus_core"
path = "src/lib.rs"

[dependencies]
reqwest = { workspace = true }
tokio = { workspace = true }
clap = { workspace = true }
ratatui = { workspace = true }
tokio-stream = { workspace = true }
uuid = { workspace = true }
quick-xml = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
dotenvy = "0.15"
crossterm = "0.28"
textwrap = "0.16"
futures = "0.3"
thiserror = "1"
quick-xml-to-json = "0.1.0"

[dev-dependencies]
mockito = "1.3"

