[package]
name = "nexus_logger"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nexus-logger"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
tokio = { workspace = true, features = ["full"] }
anyhow = "1.0"
thiserror = "2.0"
device_query = "3.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.38", features = ["serde"] }
ctrlc = "3.4"
uuid = { workspace = true }
log = "0.4.22"
nexus-core = { path = "../nexus_core" }
nexus-screen = { path = "../nexus_screen" }
tempfile = "3.10"
tray-icon = "0.21"
image = "0.25"
crossbeam-channel = "0.5"

[target.'cfg(target_os = "linux")'.dependencies]
gtk = "0.18"
