[package]
name = "nexus-screen"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nexus-screen"
path = "src/main.rs"


[dependencies]
ratatui = { workspace = true }
crossterm = "0.28"
tokio = { workspace = true, features = ["full"] }
anyhow = "1.0"
clap = { workspace = true }
thiserror = "2.0"
chrono = "0.4.38"
ctrlc = "3.4"
log = "0.4.22"
simplelog = "0.12.2"
reqwest = { workspace = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
ffmpeg-next = { git = "https://github.com/zmwangx/rust-ffmpeg" }
image = "0.25"

