[package]
name = "nexus"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nexus"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
anyhow = "1.0"
nexus-recorder = { path = "../nexus_recorder" }
tokio = { workspace = true }
nexus-gui = { path = "../nexus_gui" }
nexus-core = { path = "../nexus_core" }
nexus_mcp = { path = "../nexus_mcp" }
log = "0.4.22"
simplelog = "0.12.2"
chrono = "0.4.38"
crossterm = "0.28"
ratatui = { workspace = true }
serde_json = "1"